name: "✨ On push to main branch"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
#  build:
#    name: '🧪 Build & test Code'
#    uses: ./.github/workflows/build.yaml
#    secrets: inherit

  publish-docs:
    name: '️‍📚️ Publish Docs'
    uses: ./.github/workflows/docs.yml
